# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modul_inf_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qgis_klasaDialogBase(object):
    def setupUi(self, qgis_klasaDialogBase):
        qgis_klasaDialogBase.setObjectName("qgis_klasaDialogBase")
        qgis_klasaDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(qgis_klasaDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(qgis_klasaDialogBase)
        self.button_box.accepted.connect(qgis_klasaDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(qgis_klasaDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(qgis_klasaDialogBase)

    def retranslateUi(self, qgis_klasaDialogBase):
        _translate = QtCore.QCoreApplication.translate
        qgis_klasaDialogBase.setWindowTitle(_translate("qgis_klasaDialogBase", "proj2_inf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qgis_klasaDialogBase = QtWidgets.QDialog()
    ui = Ui_qgis_klasaDialogBase()
    ui.setupUi(qgis_klasaDialogBase)
    qgis_klasaDialogBase.show()
    sys.exit(app.exec_())
